In [1]:
import numpy as np

In [3]:
#creating array from python list

L=list(range(10))
np.array(L)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
np.array([1,2,3.,4])

array([1., 2., 3., 4.])

In [6]:
np.array([1,2,3,4],dtype='float')

array([1., 2., 3., 4.])

In [7]:
#nested list result in multi-dimentional array
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
np.array([range(i,i+4) for i in [2,4,6]])

array([[2, 3, 4, 5],
       [4, 5, 6, 7],
       [6, 7, 8, 9]])

### creating arrays from scratch

In [10]:
#create length 10 integer array filled with zeros
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
# Create a 3x5 floating-point array filled with ones
np.ones((3,4),dtype='float')

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# Create a 3x5 array filled with 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3,3))

array([[0.23483493, 0.94229186, 0.26295331],
       [0.28995369, 0.0967638 , 0.49097811],
       [0.3673073 , 0.26395261, 0.33198539]])

In [21]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[ 1.39098694,  0.75109762,  0.88976012],
       [ 1.64044303,  1.34410327,  0.91006382],
       [ 1.27773185, -0.95231711, -0.82657101]])

In [22]:
# Create a 3x3 array of random integers in the interval [0, 10]
np.random.randint(0,10,(3,3))

array([[0, 3, 7],
       [8, 3, 6],
       [4, 6, 0]])

In [23]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

### Numpy Array Attributes

In [26]:
np.random.seed(0) #seed is for reproducibility

x1=np.random.randint(10,size=6) #1-D array
x2=np.random.randint(10,size=(3,4)) #2-D array
x3=np.random.randint(10,size=(3,4,5)) #3-d array

In [32]:
print(x1)
print('x1 dim:',x1.ndim)
print('x1 shape:',x1.shape)
print('x1 size:',x1.size)
print('*'*50)

print(x2)
print('x2 dim:',x2.ndim)
print('x2 shape:',x2.shape)
print('x2 size:',x2.size)
print('*'*50)

print(x3)
print('x3 dim:',x3.ndim)
print('x3 shape:',x3.shape)
print('x3 size:',x3.size)

[5 0 3 3 7 9]
x1 dim: 1
x1 shape: (6,)
x1 size: 6
**************************************************
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
x2 dim: 2
x2 shape: (3, 4)
x2 size: 12
**************************************************
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
x3 dim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [33]:
print('dtype:',x1.dtype)

dtype: int32


In [35]:
print('itemsize:',x3.itemsize,'bytes')
print('nbytes:',x3.nbytes,'bytes')

itemsize: 4 bytes
nbytes: 240 bytes


### Array Indexing : accessing single element

In [36]:
x1

array([5, 0, 3, 3, 7, 9])

In [37]:
x1[0]

5

In [38]:
x1[-1]

9

In [39]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [41]:
x2[0]

array([3, 5, 2, 4])

In [42]:
x2[0,0]

3

In [43]:
x2[-1,1]

6

In [44]:
x2[-1,1]=12

In [45]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1, 12,  7,  7]])

### Array slicing: accessing subarrays

x[start:stop:step]

#### 1. 1-D array

In [46]:
x=np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
x[:5] #first five elements

array([0, 1, 2, 3, 4])

In [48]:
x[5:] #elements after index 5

array([5, 6, 7, 8, 9])

In [49]:
x[5:8] #middle subarray

array([5, 6, 7])

In [50]:
x[::2] #every other element

array([0, 2, 4, 6, 8])

In [51]:
x[1::2] #every other element from index 1

array([1, 3, 5, 7, 9])

In [52]:
x[::-1] #all elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 2. Multi-dimentional array

In [53]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1, 12,  7,  7]])

In [54]:
x2[:2,:3] #two rows and three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [55]:
x2[:,::2] #all rows and every other column

array([[3, 2],
       [7, 8],
       [1, 7]])

In [56]:
x2[::-1,::-1] #all reversed

array([[ 7,  7, 12,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5,  3]])

In [58]:
x2[:,:1] #first column of x2

array([[3],
       [7],
       [1]])

In [59]:
x2[:1,:] #first row of x2

array([[3, 5, 2, 4]])

In [60]:
x2[0]

array([3, 5, 2, 4])

#### Copying array

In [63]:
x_copy=x2.copy()

In [64]:
x_copy

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1, 12,  7,  7]])

In [65]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1, 12,  7,  7]])

In [69]:
x_copy[1:2,2:3]=10

In [70]:
x_copy

array([[ 3,  5,  2,  4],
       [ 7,  6, 10,  8],
       [ 1, 12,  7,  7]])

In [71]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1, 12,  7,  7]])

### Reshaping array

In [72]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [76]:
#row vector via reshape
x.reshape(1,3)

array([[1, 2, 3]])

In [77]:
#row vector via newaxis
x[np.newaxis,:]

array([[1, 2, 3]])

In [78]:
#column vector via reshape
x.reshape(3,1)

array([[1],
       [2],
       [3]])

In [80]:
#column vector via newaxis
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

### Concatenation of arrays

In [82]:
x=np.array([1,2,3])
y=np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [83]:
np.concatenate([x2,x2])

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1, 12,  7,  7],
       [ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1, 12,  7,  7]])

In [84]:
np.concatenate([x2,x2],axis=1)

array([[ 3,  5,  2,  4,  3,  5,  2,  4],
       [ 7,  6,  8,  8,  7,  6,  8,  8],
       [ 1, 12,  7,  7,  1, 12,  7,  7]])

In [85]:
np.vstack([x,y]) #vertically stack array

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
np.hstack([x,y]) #horizontally stack array

array([1, 2, 3, 4, 5, 6])

### Splitting of array

In [94]:
x=np.array([1,2,3,4,5,5,6,3,4,5,6,7])
np.split(x,3)


[array([1, 2, 3, 4]), array([5, 5, 6, 3]), array([4, 5, 6, 7])]

In [97]:
x=np.array([1,2,3,4,5,5,6,3,4,5,6,7])
np.split(x,[3,4])


[array([1, 2, 3]), array([4]), array([5, 5, 6, 3, 4, 5, 6, 7])]

In [90]:
x = np.arange(8.0)
np.split(x, [3, 5, 6, 10])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

In [91]:
x

array([0., 1., 2., 3., 4., 5., 6., 7.])